### PR TITLE
shift-click resolves to browserify shim

### PR DESCRIPTION
**Pull request by joseph-onsip**
I was recently debugging an issue that appeared only in browserified code, and I found myself wishing that I could use the extension to jump to the [browser-specific shims][1] that browserify provides for builtin modules. This change makes it so that shift-clicking on a module resolves to its browserify shim if available, while preserving existing behavior for regular clicks and non-shimmed modules.

What do you think? Here's a test gist that requires all the shimmed modules:
https://gist.github.com/joseph-onsip/0cbfdbe126308202e5c4

[1]: https://github.com/substack/node-browserify/tree/11.1.0#compatibility

### CODE REVIEW

**Comment by joseph-onsip** [comment]
Hmm, not sure what's going on with the tests. For what it's worth, locally running `npm test` against master (20d746aaf88e534528c3eb744f2d55db5bf5f736) shows me the same failures.

**Comment by stefanbuck** [comment]
Hi there, I'm on vacation this week and I need some time to take a closer look at this :wink:

**Comment by stefanbuck** [comment]
A couple of weeks ago I run into the same situation with [electron](https://github.com/atom/electron) packages. I'm not a big fan of hidden features / options like this. It would be better if the extension could verify if the repository is a browserify or in my case an electron project, but how? Perhaps a look into the `package.json` file could give us a hint about that. But I'm still not convinced that this approach is stable enough. What do you think?

**Comment by joseph-onsip** [comment]
Yeah, the hidden aspect of it was irking me as well. I considered trying to use `package.json` to determine whether the project is browserifiable (say, if `browserify` is in the `devDependencies`, or there's a [`browser` field](https://gist.github.com/defunctzombie/4339901)), but I also realized that it wouldn't be reliable.

What if we made the shim show up to the side when you hover over the link? This would make it more obvious than needing to use the shift key, and also would be extensible for electron packages (and others).

**Comment by stefanbuck** [comment]
Mhhh, I'm not sure if I like it or not to show up multiple links. I would like to postpone this feature a bit, because I'm working on a rewrite of the extension which should maybe also cover that.

Currently I'm busy with a $$ project, but I will push a first rough concept of the next version by end of the next week to get some feedback on it.

**Comment by joseph-onsip** [comment]
Yeah, having multiple links show up on hover would definitely change the scope/feel of the project, so it makes sense to hold off. Keep me posted on the rewrite, I'd love to try it out!

**Comment by stefanbuck** [comment]
Sure, I will do. Hopefully you are not disappointed that only one of your PR's landed in the extension ... for now :wink:

**Comment by joseph-onsip** [comment]
Oh, not at all! I knew they weren't sure things, especially given the [notice](https://github.com/github-linker/core#this-repository-will-be-merged-with-chrome-extension--repository-soon) about the rewrite. I just wanted to get the ideas out there, and since I figured out an implementation along the way, I thought I may as well make the PR. :+1:

**Pull request closed without merging**
