### PR TITLE
Support for es6

### PR DESCRIPTION
**Pull request by eligolding**
Links modules that are imported using the new es6 `import` syntax. Also adds support for files ending in `.es6`.

### CODE REVIEW

**Comment by stefanbuck** [comment]
Good job @eligolding :+1: 

Unfortunately I'm not at home, but I will try to take a look on it soon as possible. Could you might be add a test for the `import` stuff, in the mean time? Just add a fixture file like [require.coffee](https://github.com/github-linker/core/blob/master/test/fixtures/require.coffee) and a test [test_require_coffee](https://github.com/github-linker/core/blob/master/test/test_require_coffee.js)

No worries about failing tests. This will work soon as the PR get merged :wink: 

Thanks a lot

**Comment by eligolding** [comment]
@stefanbuck tests are done. Copy and Paste Driven Development FTW :wink: 
Anything else I need to do?

**Comment by stefanbuck** [comment]
Looks good, but what about testing two more import case? Just to be sure that everything works fine. After that I will press the button.

```js
import * as dash from "lodash";
import exp, {pick, omit} from "lodash";
```

**Comment by eligolding** [comment]
Sure. Do i also need to add a require.es6.html file?

**Comment by stefanbuck** [comment]
No, I will add it after the merge. By that It's easier to get the source code of your fixture file `require.es6`.

**Comment by eligolding** [comment]
Done. I did a squash commit and force pushed so the history is a little cleaner.

**Comment by stefanbuck** [comment]
Perfect

**Comment by eligolding** [comment]
Thank you!

**Pull request merged**
