### PR TITLE
Fix: module names not resolving due to space

### PR DESCRIPTION
**Pull request by shidhincr**
Issue: Try to use Github-linker here in this file,

https://github.com/namshi/roger/blob/master/src/client/components/buildHistory.jsx

Clicking on react leads to https://www.npmjs.com/package/%20react because of the extra space.

### CODE REVIEW

**Comment by stefanbuck** [comment]
Hi @shidhincr,

thanks for this PR. Could please add a test for it to be ensure it will not break in future. Thank you.

**Comment by shidhincr** [comment]
@stefanbuck Sure. Will add a test and ping you

**Comment by shidhincr** [comment]
@stefanbuck I updated the test. Please have a look

**Comment by stefanbuck** [comment]
Thanks :+1:

**Comment by shidhincr** [comment]
:+1:

**Pull request merged**
